---
name: dags-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - setuptools_scm
  - toml

  # Documentation
  - sphinx
  - sphinx-copybutton
  - sphinx-panels
  - pydata-sphinx-theme>=0.3.0
  - pip:
      - ../
